# Copyright 2018, IBM.
#
# This source code is licensed under the Apache License, Version 2.0 found in
# the LICENSE.txt file in the root directory of this source tree.

notifications:
    on_success: change
    on_failure: always

cache: pip
sudo: false
os: linux
dist: trusty

language: python
python:
  - "3.6"

stage_dependencies: &stage_dependencies
  # Install Qiskit Terra from master branch
  env: 
    - CMAKE_FLAGS="-D CMAKE_CXX_COMPILER=g++-5 -D ENABLE_TARGETS_QA=False -D WHEEL_TAG=-pmanylinux1_x86_64 -D STATIC_LINKING=True"
  addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - liblapack-dev
            - libblas-dev
            - g++-5
  before_install:
    # download Qiskit Terra master and unzip it only if not in stable branch, otherwise use the pypi version
    - |
      if [ ${TRAVIS_BRANCH} != "stable" ]; then
        wget https://codeload.github.com/Qiskit/qiskit-terra/zip/master -O /tmp/qiskit-terra.zip
        unzip /tmp/qiskit-terra.zip -d /tmp/
        # Install Qiskit Terra requirements.
        pip install -U -r /tmp/qiskit-terra-master/requirements.txt
        pip install -U -r /tmp/qiskit-terra-master/requirements-dev.txt
        # Create the basic cmake structure, setting out/ as the default dir.
        cd /tmp/qiskit-terra-master
        mkdir out && cd out && cmake $CMAKE_FLAGS ..
        # Compile the executables
        make
        # Install local Qiskit Terra
        pip install -e /tmp/qiskit-terra-master
        # back to current repo directory
        cd $TRAVIS_BUILD_DIR
      fi
  install:
    # install Aqua and dev requirements
    - pip install -e $TRAVIS_BUILD_DIR
    - pip install -U -r requirements-dev.txt

# Define the order of the stages.
stages:
  - test first half
  - test second half
  - deploy doc

jobs:
  include:
    - stage: test first half
      <<: *stage_dependencies
      script: 
        - python test/customtests.py 0 -end 17

    - stage: test second half
      <<: *stage_dependencies
      script: 
        - python test/customtests.py 17

    # github pages documentation update
    - stage: deploy doc
      if: branch = stable and repo = Qiskit/aqua and type = push
      install:
        # download Qiskit Terra stable branch and unzip it
        - wget https://codeload.github.com/Qiskit/qiskit-terra/zip/stable -O /tmp/qiskit-terra.zip
        - unzip /tmp/qiskit-terra.zip -d /tmp/
        - mv /tmp/qiskit-terra-stable $TRAVIS_BUILD_DIR/../qiskit-terra
        # install Qiskit Terra and dev requirements
        - pip install -e $TRAVIS_BUILD_DIR/../qiskit-terra
        - pip install -U -r $TRAVIS_BUILD_DIR/../qiskit-terra/requirements-dev.txt
        # download Aqua Chemistry stable branch and unzip it
        - wget https://codeload.github.com/Qiskit/aqua-chemistry/zip/stable -O /tmp/aqua-chemistry.zip
        - unzip /tmp/aqua-chemistry.zip -d /tmp/
        - mv /tmp/aqua-chemistry-stable $TRAVIS_BUILD_DIR/../aqua-chemistry
      script:
        # install Aqua and dev requirements
        - pip install -e $TRAVIS_BUILD_DIR
        - pip install -U -r requirements-dev.txt
        # install Aqua Chemistry and dev requirements
        - pip install -e $TRAVIS_BUILD_DIR/../aqua-chemistry
        - pip install -U -r $TRAVIS_BUILD_DIR/../aqua-chemistry/requirements-dev.txt
      deploy:
        provider: script
        skip_cleanup: true
        script: tools/ghpages_documentation_deploy.sh
        on:
          branch: stable 